name: Deploy OpenSID

# Event yang memicu workflow
on:
  push:
    branches:
      - main

# Job untuk CI/CD
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

    # Setup Terraform (Auto-detect latest version)
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

    # Terraform Init
      - name: Terraform Init
        run: terraform init

    # Terraform Apply
      - name: Terraform Apply
        env:
          TF_VAR_name_prefix: "workflow-prefix"
          TF_VAR_bucket_name: "workflow-bucket"
        run: terraform apply -auto-approve

    # Step 3: Setup Docker
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t opensid-app ./docker

    - name: Push Docker Image
      run: docker push opensid-app

    # Step 4: Deploy to Kubernetes
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./kubernetes/deployments/opensid-deployment.yml
        kubectl apply -f ./kubernetes/deployments/opensid-service.yml

    # Step 5: Monitoring Setup
    - name: Configure Prometheus & Grafana
      run: docker-compose up -d
      working-directory: ./monitoring

