name: Deploy OpenSID

# Event yang memicu workflow
on:
  push:
    branches:
      - main

# Job untuk CI/CD
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Kode
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5



    # Step 3: Terraform Init
    - name: Initialize Terraform
      run: terraform init
      working-directory: ./infrastructure/terraform

    - name: Plan Terraform
      run: terraform plan
      working-directory: ./infrastructure/terraform

    # Step 4: Terraform Plan
    - name: Terraform Plan
      run: terraform plan

    # Step 5: Terraform Apply
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./infrastructure/terraform

    # Step 3: Setup Docker
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t opensid-app ./docker

    - name: Push Docker Image
      run: docker push opensid-app

    # Step 4: Deploy to Kubernetes
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./kubernetes/deployments/opensid-deployment.yml
        kubectl apply -f ./kubernetes/deployments/opensid-service.yml

    # Step 5: Monitoring Setup
    - name: Configure Prometheus & Grafana
      run: docker-compose up -d
      working-directory: ./monitoring

